controller_joint_names: ['', 'joint_l1', 'joint_l2', 'joint_l3', 'joint_l4', 'joint_l5', 'joint_l6', 'joint_l8', 'joint_r1', 'joint_r2', 'joint_r3', 'joint_r4', 'joint_r5', 'joint_r6', 'joint_r8', 'joint_b1', ]
